"""Seed data for Unseen film - 41 shots from 03_shot-list.md
Statuses derived from PROGRESS.md FULL SHOT STATUS table.
"""

UNSEEN_FILM = {
    "title": "Unseen",
    "description": "Solo AI short film. ~3 min runtime. 5 locations. 41 shots.",
    "deadline": "2026-05-29",
    "total_shots": 41,
    "status": "IN PRODUCTION",
}

# Status legend mapping from PROGRESS.md:
#   ✅ edited -> FINAL
#   🟡 generated, not edited -> IN PROGRESS
#   ❌ cut -> CUT
#   ☐ not started -> NOT STARTED

UNSEEN_SHOTS = [
    {
        "shot_number": "01", "act": "ACT 1", "filename": "ACT1_SHOT01_CAFE_ECU",
        "model_assigned": "Kling 3.0", "shot_type": "ECU", "location": "Coffee Shop — Counter",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Bell centered, tight. Finger enters from top of frame.",
        "action_summary": "Finger presses bell. DING. Finger withdraws. Bell settles.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "DING — clean metallic ring, resonance decays",
        "special_notes": "Opening frame. Bell worn, not shiny. Finger: gender and character not yet identifiable.",
        "status": "FINAL", "duration": "4s",
    },
    {
        "shot_number": "02", "act": "ACT 1", "filename": "ACT1_SHOT02_CAFE_WS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "WS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level, wide. Woman visible at back table. Room occupies foreground.",
        "action_summary": "Café settling. Ambient movement. Woman at back table — no phone, no book.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Room tone — low ambient conversation, distant coffee equipment",
        "special_notes": "Woman should not be central — room dominates. Establish space first.",
        "status": "FINAL", "duration": "8s",
    },
    {
        "shot_number": "03", "act": "ACT 1", "filename": "ACT1_SHOT03_WOMAN_MS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Woman left-of-frame. Room behind her in soft focus.",
        "action_summary": "She watches the room. Slight head turn left, then right. Returns forward.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Room tone continues",
        "special_notes": "Observational only. No expression change. No emotional cue.",
        "status": "FINAL", "duration": "6s",
    },
    {
        "shot_number": "04", "act": "ACT 1", "filename": "ACT1_SHOT04_STEAM_INS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "Insert", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close on cup at adjacent table. Steam in focus. Background soft.",
        "action_summary": "Steam rises from cup. Thins. Disappears.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Room tone — low",
        "special_notes": "Environmental insert. No character visible.",
        "status": "FINAL", "duration": "4s",
    },
    {
        "shot_number": "05", "act": "ACT 1", "filename": "ACT1_SHOT05_CHAIR_INS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "Insert", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close on chair leg and floor tile.",
        "action_summary": "Chair leg shifts slightly against tile.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Soft scrape — brief",
        "special_notes": "No face, no hands. Micro-environmental event only.",
        "status": "FINAL", "duration": "3s",
    },
    {
        "shot_number": "06", "act": "ACT 1", "filename": "ACT1_SHOT06_BELL_INS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "Insert", "location": "Coffee Shop — Counter",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close on bell resting on counter. Same angle as Shot 01.",
        "action_summary": "Bell rests. Still. No movement.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Faint room tone",
        "special_notes": "CUT — replaced by edit pull from Shot 01 tail.",
        "status": "CUT", "duration": "3s",
    },
    {
        "shot_number": "07A", "act": "ACT 1", "filename": "ACT1_SHOT07A_WOMAN_NOTICE_MS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Woman seated on bench, left of center.",
        "action_summary": "She pauses. Her eyes drift sideways to the bench beside her — mild curiosity, not recognition. One beat.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Room tone",
        "special_notes": "Forgotten diary discovery. Expression: curiosity only — not startled, not emotional. Soul ID active.",
        "status": "FINAL", "duration": "4s",
    },
    {
        "shot_number": "07B", "act": "ACT 1", "filename": "ACT1_SHOT07B_DIARY_HIDDEN_INS",
        "model_assigned": "Kling 3.0", "shot_type": "Insert", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close on bench surface. Diary half-tucked under cushion edge.",
        "action_summary": "Diary rests still, partially hidden under the bench cushion. Nothing moves.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Room tone — low",
        "special_notes": "Her POV insert. Diary: worn, plain cover. Cushion edge visible above it. No hands in frame yet. Seedream still as reference.",
        "status": "FINAL", "duration": "3s",
    },
    {
        "shot_number": "07C", "act": "ACT 1", "filename": "ACT1_SHOT07C_DIARY_PICKUP_CU",
        "model_assigned": "Kling 3.0", "shot_type": "CU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close on bench and cushion. Her hand enters frame.",
        "action_summary": "Her hand lifts the cushion edge. Retrieves the diary. Withdraws from frame. Deliberate — not tentative.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Soft fabric sound — cushion lift",
        "special_notes": "START STATE: diary half-tucked under cushion. END STATE: diary removed, cushion settled back. No face visible.",
        "status": "FINAL", "duration": "5s",
    },
    {
        "shot_number": "07D", "act": "ACT 1", "filename": "ACT1_SHOT07D_DIARY_OPEN_CU",
        "model_assigned": "Kling 3.0", "shot_type": "CU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close on table surface. Her hands and the diary.",
        "action_summary": "She sets the diary on the table. Her hands open it to the first page.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Page opening — soft",
        "special_notes": "START STATE: closed diary in hands. END STATE: diary open on table, hands resting near it. Leads directly into Shot 07E.",
        "status": "FINAL", "duration": "4s",
    },
    {
        "shot_number": "07E", "act": "ACT 1", "filename": "ACT1_SHOT07E_DIARY_ENTRY_INS",
        "model_assigned": "Kling 3.0", "shot_type": "ECU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Top-down. Open diary centered, wooden table visible around margins.",
        "action_summary": "Diary rests open. First handwritten entry clearly legible. Ambient only — faint slow shift in tungsten highlight on page.",
        "emotion_level": 1, "camera": "Static, locked-off",
        "audio_notes": "Room tone",
        "special_notes": "ADDED DRAFT 04 (2026-04-21). Two-stage: Seedream 5.0 Lite bakes legible text into still → Kling 3.0 I2V animates ambient-only. Text must stay frozen. Precedes DIARY V.O. 1.",
        "status": "IN PROGRESS", "duration": "4s",
    },
    {
        "shot_number": "08", "act": "ACT 1", "filename": "ACT1_SHOT08_WOMAN_READ_MS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Woman at table. Diary open in front of her. Eyes down.",
        "action_summary": "She reads. Eyes track down the page. One blink.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Room tone",
        "special_notes": "DIARY V.O. 1 plays over this shot.",
        "status": "FINAL", "duration": "6s",
    },
    {
        "shot_number": "09", "act": "ACT 1", "filename": "ACT1_SHOT09_COUPLE_MS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Counter in frame. Couple in foreground.",
        "action_summary": "One person gestures at the menu board. The other hesitates. Neither decides quickly.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Murmur — indistinct, no dialogue audible",
        "special_notes": "Her POV. Background characters. No distinguishing features needed.",
        "status": "FINAL", "duration": "5s",
    },
    {
        "shot_number": "10", "act": "ACT 1", "filename": "ACT1_SHOT10_COINS_INS",
        "model_assigned": "Kling 3.0", "shot_type": "Insert", "location": "Coffee Shop — Counter",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "ECU on counter surface. Two sets of hands — coins exchanged.",
        "action_summary": "Coins pass from one hand to another across the counter.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Coin exchange — small sound",
        "special_notes": "Neither hand belongs to a named character.",
        "status": "FINAL", "duration": "3s",
    },
    {
        "shot_number": "11", "act": "ACT 1", "filename": "ACT1_SHOT11_MAN_ENTER_WS",
        "model_assigned": "Kling 3.0", "shot_type": "WS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Entrance visible. Seating area in frame.",
        "action_summary": "A man stops at the entrance. Scans the room. Crosses to a table. Sits.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Footsteps — soft on tile",
        "special_notes": "Background character. No distinguishing features needed.",
        "status": "FINAL", "duration": "6s",
    },
    {
        "shot_number": "12", "act": "ACT 1", "filename": "ACT1_SHOT12_SHADOW_CU",
        "model_assigned": "Kling 3.0", "shot_type": "CU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close on open diary page.",
        "action_summary": "Shadow crosses the open page from left to right. Her hand enters frame and half-closes the diary.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Room tone — ambient drops fractionally",
        "special_notes": "Shadow = waiter passing. She does not look up. Diary half-closed, not shut.",
        "status": "IN PROGRESS", "duration": "4s",
    },
    {
        "shot_number": "13", "act": "ACT 1", "filename": "ACT1_SHOT13_WAITER_BLUR_MS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Woman sharp in foreground. Background shallow — waiter visible as blur.",
        "action_summary": "Waiter crosses behind her. Out of focus throughout. Movement even, practiced. He passes and is gone.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Soft footfall behind her",
        "special_notes": "CRITICAL: Waiter must be unidentifiable — fully out of focus. Face must not resolve at any point. Shallow depth of field in prompt.",
        "status": "NOT STARTED", "duration": "5s",
    },
    {
        "shot_number": "14", "act": "ACT 1", "filename": "ACT1_SHOT14_PAGE_TURN_CU",
        "model_assigned": "Kling 3.0", "shot_type": "CU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close on diary. Her hands visible.",
        "action_summary": "Diary opens again. She turns a page.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Page turn — soft",
        "special_notes": "DIARY V.O. 3 over this shot. Transition out of Act 1.",
        "status": "IN PROGRESS", "duration": "4s",
    },
    {
        "shot_number": "15", "act": "ACT 2", "filename": "ACT2_SHOT01_CONCOURSE_WS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "WS", "location": "Indoor Concourse",
        "int_ext": "INT", "time_of_day": "Day",
        "framing": "Eye level. Wide. High ceilings visible. Foot traffic across full frame.",
        "action_summary": "People cross the concourse in both directions. Steady flow. No named character in frame.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Ambient concourse — footfall, distant PA, indistinct voices",
        "special_notes": "Establishing. Figure not yet present. Grammar: neutral overhead light, institutional surfaces.",
        "status": "NOT STARTED", "duration": "8s",
    },
    {
        "shot_number": "16", "act": "ACT 2", "filename": "ACT2_SHOT02_CONCOURSE_MS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "MS", "location": "Indoor Concourse",
        "int_ext": "INT", "time_of_day": "Day",
        "framing": "Eye level. Figure left-of-frame near wall. Crowd fills center and right.",
        "action_summary": "Figure stands near wall. Still. Crowd passes in both directions. No one adjusts for him. No eye contact made.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Ambient continues",
        "special_notes": "Plain dark work clothing — no waiter uniform. Not performing stillness — just still. DIARY V.O. 4 over.",
        "status": "NOT STARTED", "duration": "8s",
    },
    {
        "shot_number": "17", "act": "ACT 2", "filename": "ACT2_SHOT03_WALKWAY_WS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "WS", "location": "Tourist Walkway",
        "int_ext": "EXT", "time_of_day": "Day",
        "framing": "Eye level. Wide. Pedestrian path visible. Tourist clusters in frame.",
        "action_summary": "Tourists move slowly. Groups stop to photograph. Light wind.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Outdoor ambient — light wind, distant voices, camera shutters",
        "special_notes": "Establishing. Overcast or diffuse light. No golden hour. No dramatic sky.",
        "status": "NOT STARTED", "duration": "8s",
    },
    {
        "shot_number": "18", "act": "ACT 2", "filename": "ACT2_SHOT04_WALKWAY_MS",
        "model_assigned": "Kling 3.0", "shot_type": "MS", "location": "Tourist Walkway",
        "int_ext": "EXT", "time_of_day": "Day",
        "framing": "Eye level. Figure center-left. Tourist group to his right.",
        "action_summary": "A tourist hands their phone to the Figure. He raises it. Takes the photo. Returns the device. No one turns to include the Figure in a photograph.",
        "emotion_level": 2, "camera": "Static",
        "audio_notes": "Tourist ambient. Single camera shutter.",
        "special_notes": "Script revision 2026-04-21: Figure photographs tourists — he frames others; no one frames him. Irony inverted. Model rerouted Veo → Kling.",
        "status": "IN PROGRESS", "duration": "8s",
    },
    {
        "shot_number": "19", "act": "ACT 2", "filename": "ACT2_SHOT05_HUB_WS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "WS", "location": "Transport Hub",
        "int_ext": "INT", "time_of_day": "Day",
        "framing": "Eye level. Wide. Vehicles, stalls, and boarding passengers all visible.",
        "action_summary": "People board. Drivers wait. Vendors arrange stalls. Functional movement throughout.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Hub ambient — idling engines, footfall, indistinct vendor sounds",
        "special_notes": "Establishing. Figure not yet in frame.",
        "status": "NOT STARTED", "duration": "8s",
    },
    {
        "shot_number": "20", "act": "ACT 2", "filename": "ACT2_SHOT06_HUB_MS",
        "model_assigned": "Kling 3.0", "shot_type": "MS", "location": "Transport Hub",
        "int_ext": "INT", "time_of_day": "Day",
        "framing": "Eye level. Figure at left edge of frame. Activity continues behind him.",
        "action_summary": "Figure picks up a piece of litter. Drops it in a bin. Steps aside for a passing family. Moves on.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Ambient continues",
        "special_notes": "Each action precise and completed — no hesitation, no looking around. DIARY V.O. 6 over.",
        "status": "IN PROGRESS", "duration": "8s",
    },
    {
        "shot_number": "21", "act": "ACT 2", "filename": "ACT2_SHOT07_HUB_STOP_MS",
        "model_assigned": "Kling 3.0", "shot_type": "MS", "location": "Transport Hub",
        "int_ext": "INT", "time_of_day": "Day",
        "framing": "Same or slightly tighter on Figure mid-movement.",
        "action_summary": "A DING bleeds through. Figure stops mid-stride. He looks up — not a flinch. A moment of recognition.",
        "emotion_level": 2, "camera": "Static",
        "audio_notes": "DING — distant, metallic, sharp against hub ambient",
        "special_notes": "Bell intrudes from café reality. Not a flinch — a moment of recognition.",
        "status": "IN PROGRESS", "duration": "4s",
    },
    {
        "shot_number": "21A", "act": "ACT 2", "filename": "ACT2_SHOT07A_JANE_LOOKUP_MS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Jane at her table. Diary in front of her. Counter visible in background.",
        "action_summary": "Jane looks up from the diary. Her eyes move toward the counter. Expression neutral — present, not startled.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Café room tone. DING echo fading.",
        "special_notes": "CUT-BACK from Hub — cross-cuts with Shot 21. No DIARY V.O. Script revision 2026-04-21.",
        "status": "NOT STARTED", "duration": "4s",
    },
    {
        "shot_number": "21B", "act": "ACT 2", "filename": "ACT2_SHOT07B_COUNTER_POV_MS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "MS", "location": "Coffee Shop — Counter",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Jane's POV. Counter in frame. Bell on counter. Waiter visible in background.",
        "action_summary": "Service bell on counter — just sounded. Waiter picks up two coffee mugs and moves away from counter. Bell settles.",
        "emotion_level": 2, "camera": "Static",
        "audio_notes": "Café ambient. Bell resonance decays. Cup movement sounds.",
        "special_notes": "Jane's POV — follows Shot 21A. Waiter face must not resolve. First visual link: Figure (Hub) and Waiter (Café) connected by the same DING.",
        "status": "NOT STARTED", "duration": "5s",
    },
    {
        "shot_number": "22", "act": "ACT 2", "filename": "ACT2_SHOT08_CORRIDOR_WS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "WS", "location": "Back-of-House Corridor",
        "int_ext": "INT", "time_of_day": "Day",
        "framing": "Eye level. Wide. Long narrow corridor. Strip lighting overhead.",
        "action_summary": "Empty corridor. Still. Strip lighting. Institutional walls.",
        "emotion_level": 0, "camera": "Static",
        "audio_notes": "Strip light hum — low, constant",
        "special_notes": "No character. Space contracts after Act 2's wide exteriors. Establish the narrowness.",
        "status": "NOT STARTED", "duration": "5s",
    },
    {
        "shot_number": "23", "act": "ACT 2", "filename": "ACT2_SHOT09_CORRIDOR_MS",
        "model_assigned": "Kling 3.0", "shot_type": "MS", "location": "Back-of-House Corridor",
        "int_ext": "INT", "time_of_day": "Day",
        "framing": "Eye level. Figure mid-frame. Chairs along wall visible behind him.",
        "action_summary": "Figure straightens a chair. Aligns two objects on a shelf. Pulls a door closed that was left open. Returns to the chairs.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Soft: chair on floor, shelf objects adjusted, door latch",
        "special_notes": "No one passes through. No acknowledgment. DIARY V.O. 7 over.",
        "status": "NOT STARTED", "duration": "8s",
    },
    {
        "shot_number": "24", "act": "ACT 2", "filename": "ACT2_SHOT10_HANDS_CU",
        "model_assigned": "Kling 3.0", "shot_type": "CU", "location": "Back-of-House Corridor",
        "int_ext": "INT", "time_of_day": "Day",
        "framing": "Close on Figure's hands and the chair being straightened. Hands fill the frame.",
        "action_summary": "His hands straighten the last chair. Come to rest on the back of it. Still.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Chair settles — quiet",
        "special_notes": "MATCH CUT POINT. Frame: hands centered, chair back visible, corridor floor below. Must match Shot 25 exactly in framing and action.",
        "status": "NOT STARTED", "duration": "4s",
    },
    {
        "shot_number": "25", "act": "ACT 3", "filename": "ACT3_SHOT01_HANDS_MATCH_CU",
        "model_assigned": "Kling 3.0", "shot_type": "CU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Identical framing to Shot 24. Close on hands and chair back.",
        "action_summary": "Waiter's hands straighten the last chair at an adjacent table. Hands come to rest. Still.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Chair settles — café room tone returns on cut",
        "special_notes": "MATCH CUT ARRIVAL. Frame must be identical to Shot 24. Generate Shots 24 and 25 in the same Kling session.",
        "status": "NOT STARTED", "duration": "4s",
    },
    {
        "shot_number": "26", "act": "ACT 3", "filename": "ACT3_SHOT02_WAITER_TABLE_MS",
        "model_assigned": "Kling 3.0", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Waiter at adjacent table. Woman in background, slightly soft.",
        "action_summary": "Waiter wipes the table surface. Lifts the service bell and sets it back on the counter.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Table wipe — soft. Bell placed.",
        "special_notes": "First clear view of Waiter in motion — but woman is still primary subject. DIARY V.O. 8 begins.",
        "status": "NOT STARTED", "duration": "6s",
    },
    {
        "shot_number": "27", "act": "ACT 3", "filename": "ACT3_SHOT03_WOMAN_LASTPAGE_MS",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Woman at table. Diary open to final page.",
        "action_summary": "She turns to the final page. Eyes begin tracking down.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Page turn — soft",
        "special_notes": "DIARY V.O. 8 continues.",
        "status": "NOT STARTED", "duration": "5s",
    },
    {
        "shot_number": "28", "act": "ACT 3", "filename": "ACT3_SHOT04_WAITER_COUNTER_MS",
        "model_assigned": "Kling 3.0", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Waiter at far counter preparing a cup. Woman's table visible in background.",
        "action_summary": "Waiter prepares a cup. Deliberate. Unhurried.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Coffee preparation — soft ambient",
        "special_notes": "Background action. Observed, not highlighted.",
        "status": "NOT STARTED", "duration": "5s",
    },
    {
        "shot_number": "29", "act": "ACT 3", "filename": "ACT3_SHOT05_WOMAN_CU",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "CU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Closer than Shot 08. Her face and the final page.",
        "action_summary": "She reads. Eyes move slowly. One blink. Expression does not change.",
        "emotion_level": 1, "camera": "Static",
        "audio_notes": "Room tone — quieter now",
        "special_notes": "DIARY V.O. 9 and 10 over this shot. The film's most interior moment — carried in stillness, not expression.",
        "status": "NOT STARTED", "duration": "6s",
    },
    {
        "shot_number": "30", "act": "ACT 3", "filename": "ACT3_SHOT06_DIARY_CLOSE_CU",
        "model_assigned": "Kling 3.0", "shot_type": "CU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close on diary in her hands.",
        "action_summary": "She finishes reading. The diary closes. Her hands rest on the cover.",
        "emotion_level": 2, "camera": "Static",
        "audio_notes": "Diary closing — soft. Then silence.",
        "special_notes": "After the diary closes: no V.O., no ambient. Hold in silence for one full beat before cutting.",
        "status": "NOT STARTED", "duration": "5s",
    },
    {
        "shot_number": "31", "act": "ACT 3", "filename": "ACT3_SHOT07_WAITER_APPROACH_MS",
        "model_assigned": "Kling 3.0", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Wide enough to include the aisle. Waiter enters from background.",
        "action_summary": "Waiter carries a cup toward her table. Eyes directed at the table surface — not at her face. Pace measured, even.",
        "emotion_level": 3, "camera": "Static",
        "audio_notes": "Footfall — soft on tile. Room tone very low.",
        "special_notes": "First fully clear shot of Waiter in motion. Eyes down throughout. Not theatrical — functional.",
        "status": "NOT STARTED", "duration": "6s",
    },
    {
        "shot_number": "32", "act": "ACT 3", "filename": "ACT3_SHOT08_CUP_INS",
        "model_assigned": "Kling 3.0", "shot_type": "Insert", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "ECU — table surface. Cup and bell in frame.",
        "action_summary": "Cup set on table. Waiter's hand brushes the service bell as he places it back.",
        "emotion_level": 3, "camera": "Static",
        "audio_notes": "Cup placed — ceramic on wood. DING — quiet, contact only, not a full ring.",
        "special_notes": "The brush feels incidental, not staged. DING is understated here — not the clean ring of Shot 01.",
        "status": "NOT STARTED", "duration": "4s",
    },
    {
        "shot_number": "33", "act": "ACT 3", "filename": "ACT3_SHOT09_WAITER_STILL_MS",
        "model_assigned": "Kling 3.0", "shot_type": "MS", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Eye level. Waiter standing at her table. Still.",
        "action_summary": "Waiter does not move. Hands at sides. Eyes directed down.",
        "emotion_level": 4, "camera": "Static",
        "audio_notes": "Silence. No ambient.",
        "special_notes": "The pause. One full beat before she looks up. Do not undercut with ambient sound. Hold the silence.",
        "status": "NOT STARTED", "duration": "4s",
    },
    {
        "shot_number": "34", "act": "ACT 3", "filename": "ACT3_SHOT10_WOMAN_LOOKUP_CU",
        "model_assigned": "Veo 3.1 Fast", "shot_type": "CU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close. Her face. Closed diary in foreground.",
        "action_summary": "She looks up. Her eyes find him.",
        "emotion_level": 4, "camera": "Static",
        "audio_notes": "Silence continues.",
        "special_notes": "Expression: present. Not startled. Not moved. Just — looking. Emotion must not exceed 4/10.",
        "status": "NOT STARTED", "duration": "4s",
    },
    {
        "shot_number": "35", "act": "ACT 3", "filename": "ACT3_SHOT11_WAITER_EYES_CU",
        "model_assigned": "Kling 3.0", "shot_type": "CU", "location": "Coffee Shop",
        "int_ext": "INT", "time_of_day": "Morning",
        "framing": "Close. His face. Neutral background.",
        "action_summary": "He remains still. Then — slowly — his eyes lift.",
        "emotion_level": 5, "camera": "Static",
        "audio_notes": "Silence.",
        "special_notes": "FINAL SHOT. Gaze lift is slow — not emotional, mechanical. Like something being restored. CUT TO BLACK before full eye contact is made.",
        "status": "NOT STARTED", "duration": "6s",
    },
]
